from libs.portas import Portas

DEBUG = True
VELOCIDADE_PADRAO = 45
VELOCIDADE_BAIXA = 25
VELOCIDADE_BASE_SEGUIDOR = 60
VELOCIDADE_MAXIMA = 80
PORTA_SENSOR_COR_LINHA = Portas.SERIAL5
PORTA_SENSOR_COR_ESQUERDO = Portas.I2C3
CHAVE_SENSOR_COR_ESQUERDO = 'sensor_cor_lateral_esquerda'

KP_PADRAO = 0.5
KD_PADRAO = 0.5

KP_BAIXA_VELOCIDADE = 0.5
KD_BAIXA_VELOCIDADE = 0.2

VALOR_ENCRUZILHADA = 50

DEPOSITAR_DE_FRENTE = False
